build:
  main: cmd/vanity-monero/main.go
  binary: vanity-monero
  ldflags: -s -w
  goos:
    - darwin
    - linux
    - windows
  goarch:
    - amd64
    - 386
  ignore:
    - goos: darwin
      goarch: 386

archive:
  replacements:
    386: 32
    amd64: 64
    darwin: macos
  name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
  format: tar.xz
  format_overrides:
    - goos: windows
      format: zip
